language: cpp

before_install:
  - sudo apt-get -y install libginac-dev libgtest-dev
# have to build gtest and put library in /usr/lib/
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib

#copy or symlink libgtest.a and libgtest_main.a to your /usr/lib folder
sudo cp *.a /usr/lib
compiler:
  - gcc

script:
  - cmake .
  - cmake --build .
